module.exports = {
  MIN_LIQ_BUSD: Number(process.env.MIN_LIQ_BUSD || 20),
  POLL_INTERVAL: Number(process.env.POLL_INTERVAL || 70000),
  TRENDING_BATCH: Number(process.env.TRENDING_BATCH || 3),
  NEWPAIR_BATCH: Number(process.env.NEWPAIR_BATCH || 2),
  RPC_HTTP: process.env.RPC_HTTP || 'https://bsc-dataseed.binance.org/',
  BSC_WS: process.env.BSC_WS,
  FACTORY: process.env.PANCAKE_FACTORY,
  ROUTER: process.env.PANCAKE_ROUTER,
  BUSD_ADDRESS: process.env.BUSD_ADDRESS,
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
  LIVE_TRADER: (process.env.LIVE_TRADER === 'true') || false,
  PRIVATE_KEY: process.env.PRIVATE_KEY || null,
  MIN_BUY_USD: Number(process.env.MIN_BUY_USD || 1),
};
